[workspace]
resolver = "2"

members = [
    "actix",
]

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
actix-web = "4.4.0"

[profile.release]
strip = "symbols"

[profile.dev]
opt-level = 3
debug = 1