[package]
name = "example-api-nodb"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true, features = ["derive"]}
env_logger = { workspace = true }
log = { workspace = true }